const defaultMedicines = {
  // 1–50: Common Illnesses
  fever: "Paracetamol",
  viral_fever: "Paracetamol",
  cold: "Cetirizine",
  flu: "Oseltamivir",
  cough: "Dextromethorphan",
  wet_cough: "Ambroxol",
  dry_cough: "Dextromethorphan",
  sore_throat: "Azithromycin",
  sinusitis: "Amoxicillin-Clavulanic Acid",
  tonsillitis: "Azithromycin",
  strep_throat: "Consult a specialist",
  pneumonia: "Consult a specialist",
  bronchitis: "Consult a specialist",
  chest_congestion: "Ambroxol",
  headache: "Ibuprofen",
  migraine: "Sumatriptan",
  body_pain: "Ibuprofen",
  muscle_pain: "Diclofenac",
  joint_pain: "Aceclofenac",
  back_pain: "Diclofenac",
  neck_pain: "Ibuprofen",
  fatigue: "Vitamin B12",
  weakness: "ORS",
  dehydration: "ORS",

  // 51–100: Gastrointestinal
  acidity: "Pantoprazole",
  gas: "Simethicone",
  indigestion: "Domperidone",
  constipation: "Lactulose",
  diarrhea: "ORS + Zinc",
  food_poisoning: "Ciprofloxacin",
  stomach_infection: "Ofloxacin + Ornidazole",
  stomach_pain: "Dicyclomine",
  gastric_ulcer: "Omeprazole",
  duodenal_ulcer: "Pantoprazole",
  vomiting: "Ondansetron",
  nausea: "Ondansetron",
  liver_infection: "Consult a specialist",
  jaundice: "Consult a specialist",
  hepatitis: "Consult a specialist",
  pancreatitis: "Consult a specialist",
  appendicitis: "Emergency treatment required",
  IBS: "Mebeverine",
  IBD: "Consult a specialist",
  GERD: "Pantoprazole",

  // 101–150: Infections
  bacterial_infection: "Amoxicillin",
  viral_infection: "Paracetamol",
  urinary_infection: "Nitrofurantoin",
  kidney_infection: "Consult a specialist",
  UTI: "Nitrofurantoin",
  fungal_infection: "Clotrimazole",
  ringworm: "Terbinafine",
  scabies: "Permethrin",
  lice_infestation: "Permethrin Lotion",
  throat_infection: "Azithromycin",
  ear_infection: "Cefdinir",
  otitis_media: "Cefuroxime",
  eye_infection: "Chloramphenicol Drops",
  conjunctivitis: "Ofloxacin Eye Drops",
  skin_infection: "Amoxicillin-Clavulanic Acid",
  cellulitis: "Consult a specialist",
  dengue: "Paracetamol",
  malaria: "ACT Therapy",
  typhoid: "Cefixime",
  chikungunya: "Paracetamol",
  covid19: "Paracetamol + Zinc",

  // 151–200: Dermatology
  acne: "Adapalene Gel",
  eczema: "Hydrocortisone Cream",
  psoriasis: "Consult a specialist",
  dermatitis: "Hydrocortisone Cream",
  skin_rash: "Cetirizine",
  hives: "Loratadine",
  boil: "Mupirocin Ointment",
  abscess: "Consult a specialist",
  sunburn: "Aloe Vera Gel",
  hyperpigmentation: "Kojic Acid Cream",
  melasma: "Hydroquinone",
  athlete_foot: "Clotrimazole",
  nail_fungus: "Terbinafine",
  vitiligo: "Consult a specialist",
  skin_allergy: "Cetirizine",
  insect_bite: "Calamine Lotion",
  mosquito_bite: "Calamine",
  contact_dermatitis: "Hydrocortisone",

  // 201–250: Chronic Diseases
  diabetes: "Metformin",
  hypertension: "Amlodipine",
  thyroid_hypo: "Levothyroxine",
  thyroid_hyper: "Consult a specialist",
  cholesterol: "Atorvastatin",
  heartburn: "Pantoprazole",
  asthma: "Salbutamol Inhaler",
  COPD: "Consult a specialist",
  arthritis: "Aceclofenac",
  osteoarthritis: "Ibuprofen",
  rheumatoid_arthritis: "Consult a specialist",
  gout: "Allopurinol",
  anemia: "Iron + Folic Acid",
  vitamin_d_deficiency: "Vitamin D3",
  vitamin_b12_deficiency: "Methylcobalamin",
  calcium_deficiency: "Calcium + Vitamin D3",

  // 251–300: Neurological
  insomnia: "Melatonin",
  anxiety: "Hydroxyzine",
  stress: "Ashwagandha",
  depression: "Consult a specialist",
  epilepsy: "Consult a specialist",
  seizures: "Emergency care",
  tremors: "Consult a specialist",
  parkinson: "Consult a specialist",
  dementia: "Consult a specialist",
  neuralgia: "Gabapentin",
  sciatica: "Pregabalin",

  // 301–350: Women's Health
  period_pain: "Mefenamic Acid",
  PCOS: "Metformin",
  menopause_symptoms: "Consult a specialist",
  vaginal_infection: "Clotrimazole",
  yeast_infection: "Fluconazole",
  pregnancy_nausea: "Doxylamine",
  breast_pain: "Ibuprofen",
  UTI_female: "Nitrofurantoin",

  // 351–400: Men's Health
  prostate_infection: "Ciprofloxacin",
  erectile_dysfunction: "Consult a specialist",
  hair_loss: "Minoxidil",
  beard_patch: "Minoxidil",
  testicular_pain: "Consult a specialist",
  infertility: "Consult a specialist",

  // 401–450: Pediatric
  pediatric_fever: "Paracetamol Syrup",
  pediatric_cold: "Cetirizine Drops",
  teething_pain: "Paracetamol",
  pediatric_cough: "Ambroxol Drops",
  dehydration_child: "ORS",
  diarrhea_child: "ORS + Zinc",
  worm_infection_child: "Albendazole",

  // 451–500: Emergency / Injuries
  wound: "Betadine",
  cut: "Antiseptic Cream",
  burn: "Silver Sulfadiazine",
  fracture: "Emergency care",
  sprain: "Diclofenac Gel",
  muscle_strain: "Ibuprofen",
  bleeding: "Apply pressure + antiseptic",
  heatstroke: "ORS + cooling",
  frostbite: "Emergency",
  electric_shock: "Emergency",
  snake_bite: "Antivenom (hospital only)",
  dog_bite: "Rabies vaccine (hospital only)",
  food_allergy: "Cetirizine",
  anaphylaxis: "Epinephrine (hospital)",
  dehydration_severe: "IV Fluids",
  TB: "Anti-TB Therapy",
  HIV: "Antiretrovirals",
  cancer: "Oncology treatment",
  stroke: "Emergency",
  heart_attack: "Emergency",
  kidney_failure: "Dialysis",
  liver_failure: "Transplant evaluation"
};

export default defaultMedicines;